add_newline = true

[character]
success_symbol = '[->](bold fg:#ffffff)'
error_symbol = '[X](bold fg:#ff0000)'

[directory]
truncation_length = 8
truncation_symbol = '…/'

[docker_context]
format = "via [🐋 $context](bold #0000ff)"

[git_branch]
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[memory_usage]
disabled = false
threshold = -1
format = '[mem]($style) [${ram}]($style) '
symbol = ''
style = 'bold fg:#00ff00'

[username]
style_user = 'bold fg:#ff8c00'
style_root = 'bold fg:#ff0000'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[package]
disabled = true
